<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net6.0</TargetFramework>
		<GenerateAssemblyFileVersionAttribute>false</GenerateAssemblyFileVersionAttribute>
		<GenerateAssemblyInformationalVersionAttribute>false</GenerateAssemblyInformationalVersionAttribute>
		<Description>TownOfHost_ForEver</Description>
		<Authors>tukasa0001(EmptyBottle){TOH}, integral0131, AkagumaAsumu{TOH4E}, Mitsuya{TOHFE}</Authors>
		<langVersion>preview</langVersion>
		<NoWarn>MSB3246</NoWarn>
		<PackageId>TownOfHost_ForEver</PackageId>
		<Company>tukasa0001(EmptyBottle){TOH}, integral0131, AkagumaAsumu{TOH4E}, Mitsuya{TOHFE}</Company>
		<Product>TownOfHost_ForEver</Product>
		<AssemblyName>TownOfHost_ForEver</AssemblyName>
		<RootNamespace>TownOfHost_ForEver</RootNamespace>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<Nullable>enable</Nullable>
		<AmongUs>C:\Users\mitsu\Downloads\among-us-windows\AmongUsItch\Itch</AmongUs>
		<NuGetPackageRoot Condition="'$(NuGetPackageRoot)' == ''">$(UserProfile)\.nuget\packages\</NuGetPackageRoot>
	</PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
		<DefineConstants>TRACE</DefineConstants>
	</PropertyGroup>

	<ItemGroup>
		<Reference Include="$(AmongUs)\BepInEx\core\*.dll" />
		<Reference Include="$(AmongUs)\BepInEx\interop\*.dll" />
		<EmbeddedResource Include=".\Resources\*.png" />
		<EmbeddedResource Include=".\Resources\string.csv" />
		<EmbeddedResource Include=".\Resources\Sounds\**" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Costura.Fody" Version="5.7.0">
			<IncludeAssets>runtime; compile; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
			<PrivateAssets>all</PrivateAssets>
		</PackageReference>
	    <PackageReference Include="csv" Version="2.0.93" />
		<PackageReference Include="SharpDX" Version="4.2.0" />
		<PackageReference Include="SharpDX.XAudio2" Version="4.2.0" />
	    <PackageReference Include="GitInfo" Version="2.0.20">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="Modules\YouTube\" />
	</ItemGroup>

	<Target Name="Copy" AfterTargets="Build" Condition="'$(AmongUs)' != ''">
		<ItemGroup>
			<PluginCopyFiles Include="$(OutputPath)$(AssemblyName).dll" />
			<PluginCopyFiles Include="$(NuGetPackageRoot)sharpdx\4.2.0\lib\net45\SharpDX.dll" />
			<PluginCopyFiles Include="$(NuGetPackageRoot)sharpdx.xaudio2\4.2.0\lib\net45\SharpDX.XAudio2.dll" />
		</ItemGroup>
		<Delete Files="$(AmongUs)/BepInEx/plugins/TownOfHost_ForE.dll" Condition="Exists('$(AmongUs)/BepInEx/plugins/TownOfHost_ForE.dll')" />
		<Copy SourceFiles="@(PluginCopyFiles)" DestinationFolder="$(AmongUs)/BepInEx/plugins/" SkipUnchangedFiles="true" />
	</Target>
</Project>
